services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: evolution
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: user
      DB_POSTGRESDB_SCHEMA: postgresql
      DB_POSTGRESDB_PASSWORD: holamundo 
      N8N_CUSTOM_EXTENSIONS: "/data/plugins" 
      N8N_LOG_LEVEL: debug
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/data/plugins/n8n-nodes-cloudflare-ai
    restart: unless-stopped
  

  postgres:
    container_name: postgres
    image: postgres:16 
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=holamundo
      - POSTGRES_USER=user
      - POSTGRES_DB=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes: 
  postgres_data:
  n8n_data:
